SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

USE [demoDW]
GO

CREATE OR ALTER PROCEDURE LOADER_BUYING_GROUP_D AS
BEGIN

--- Let's crate a load for Buying Groups

---Variable declartion, and checkpoint logic
BEGIN

		DECLARE @CHECKPOINT DATETIME, @NEWCHECKPOINT DATETIME
		DECLARE @SOURCE_COLUMNS INT, @ROWS_INS INT, @ROWS_DEL INT, @ROWS_UPD INT, @ROWS_SKIP INT
		DECLARE @BUYING_GROUP_D_ID INT, @BUYINGGROUPID INT, @BUYINGGROUPNAME NVARCHAR(50)
		DECLARE @N_BUYINGGROUPID INT, @N_BUYINGGROUPNAME NVARCHAR(50)

		SELECT
			@CHECKPOINT = a.RUN_DT
		FROM
			(
				SELECT 
					MAX(b.RUN_DT) RUN_DT
				FROM
					(
						SELECT RUN_DT FROM [dbo].[RUNS] WHERE RUN_NAME = 'BUYING_GROUP_D'
						UNION
						SELECT CONVERT([datetime],'1990-01-01 00:00:00') RUN_DT
					)b
			) a

		SELECT @NEWCHECKPOINT = GETDATE(), @SOURCE_COLUMNS = 0, @ROWS_INS = 0, @ROWS_DEL = 0, @ROWS_UPD = 0, @ROWS_SKIP = 0

		IF @CHECKPOINT = NULL
		BEGIN
			SET @CHECKPOINT = CONVERT([datetime],'1990-01-01 00:00:00')
		END
		---Same logic as State dimension loader
		DECLARE DB_CURSOR CURSOR FOR
			SELECT
				BUYINGGROUPID
				, BUYINGGROUPNAME
			FROM
				WideWorldImporters.[Sales].BuyingGroups
			FOR SYSTEM_TIME
				BETWEEN @CHECKPOINT AND @NEWCHECKPOINT
			ORDER BY
				BUYINGGROUPID, VALIDFROM

		OPEN DB_CURSOR
		FETCH NEXT FROM DB_CURSOR INTO @BUYINGGROUPID, @BUYINGGROUPNAME

		WHILE @@FETCH_STATUS = 0
		BEGIN

			SET @SOURCE_COLUMNS = @SOURCE_COLUMNS + 1
		
			IF NOT EXISTS (SELECT BUYING_GROUP_D_ID FROM BUYING_GROUP_D WHERE GROUP_SRC_ID = @BUYINGGROUPID)
			BEGIN

				SET @ROWS_INS = @ROWS_INS + 1

				INSERT INTO BUYING_GROUP_D (GROUP_NAME, GROUP_SRC_ID) 
					VALUES (@BUYINGGROUPNAME, @BUYINGGROUPID)

			END
			ELSE
			BEGIN

				SELECT
					@N_BUYINGGROUPNAME = GROUP_NAME
				FROM
					BUYING_GROUP_D
				WHERE
					GROUP_SRC_ID = @BUYINGGROUPID

				IF @N_BUYINGGROUPNAME <> @BUYINGGROUPNAME
				BEGIN

					SET @ROWS_UPD = @ROWS_UPD + 1

					UPDATE
						BUYING_GROUP_D
					SET
						GROUP_NAME = @BUYINGGROUPNAME
						, LAST_UPDATE_DATE = GETDATE()
					WHERE
						GROUP_SRC_ID = @BUYINGGROUPID

				END
				ELSE
				BEGIN

					SET @ROWS_SKIP = @ROWS_SKIP + 1

				END

			END

			FETCH NEXT FROM DB_CURSOR INTO @BUYINGGROUPID, @BUYINGGROUPNAME

		END

		CLOSE DB_CURSOR
		DEALLOCATE DB_CURSOR

		INSERT INTO [dbo].[RUNS] (RUN_NAME, RUN_DT, SOURCE_COLUMNS, ROWS_INS, ROWS_DEL, ROWS_UPD, ROWS_SKIP) 
			VALUES ('BUYING_GROUP_D', @NEWCHECKPOINT, @SOURCE_COLUMNS, @ROWS_INS, @ROWS_DEL, @ROWS_UPD, @ROWS_SKIP)

	END

END
GO

