

CREATE OR ALTER PROCEDURE LOADER_CITY_D AS
BEGIN

	-- create LOAD CITY_D

	BEGIN

		DECLARE @CHECKPOINT DATETIME, @NEWCHECKPOINT DATETIME
		DECLARE @SOURCE_COLUMNS INT, @ROWS_INS INT, @ROWS_DEL INT, @ROWS_UPD INT, @ROWS_SKIP INT
		DECLARE @CITY_D_ID INT, @CITYID INT, @CITYNAME NVARCHAR(50), @STATEPROVINCEID INT, @STATE_D_ID INT
		DECLARE @N_CITYID INT, @N_CITYNAME NVARCHAR(50), @N_STATEPROVINCEID INT, @N_STATE_D_ID INT

		SELECT
			@CHECKPOINT = a.RUN_DT
		FROM
			(
				SELECT 
					MAX(b.RUN_DT) RUN_DT
				FROM
					(
						SELECT RUN_DT FROM [dbo].[RUNS] WHERE RUN_NAME = 'CITY_D'
						UNION
						SELECT CONVERT([datetime],'1990-01-01 00:00:00') RUN_DT
					)b
			) a

		SELECT @NEWCHECKPOINT = GETDATE(), @SOURCE_COLUMNS = 0, @ROWS_INS = 0, @ROWS_DEL = 0, @ROWS_UPD = 0, @ROWS_SKIP = 0

		IF @CHECKPOINT = NULL
		BEGIN
			SET @CHECKPOINT = CONVERT([datetime],'1990-01-01 00:00:00')
		END

		DECLARE DB_CURSOR CURSOR FOR
			SELECT
				CITYID
				, CITYNAME
				, STATEPROVINCEID
			FROM
				WideWorldImporters.[Application].Cities
			FOR SYSTEM_TIME
				BETWEEN @CHECKPOINT AND @NEWCHECKPOINT
			ORDER BY
				CITYID, VALIDFROM

		OPEN DB_CURSOR
		FETCH NEXT FROM DB_CURSOR INTO @CITYID, @CITYNAME, @STATEPROVINCEID

		WHILE @@FETCH_STATUS = 0
		BEGIN

			SET @SOURCE_COLUMNS = @SOURCE_COLUMNS + 1

			IF NOT EXISTS (SELECT STATE_D_ID FROM STATE_D WHERE STATE_SRC_ID = @STATEPROVINCEID)
			BEGIN

				SET @STATE_D_ID = -999

			END
			ELSE
			BEGIN

				SELECT @STATE_D_ID = STATE_D_ID FROM STATE_D WHERE STATE_SRC_ID = @STATEPROVINCEID

			END

			IF NOT EXISTS (SELECT CITY_D_ID FROM CITY_D WHERE CITY_SRC_ID = @CITYID)
			BEGIN

				SET @ROWS_INS = @ROWS_INS + 1

				INSERT INTO CITY_D (CITY_NAME, STATE_D_ID, CITY_SRC_ID) 
					VALUES (@CITYNAME, @STATE_D_ID, @CITYID)

			END
			ELSE
			BEGIN

				SELECT
					@N_CITYNAME = CITY_NAME
					, @N_STATE_D_ID = STATE_D_ID
				FROM
					CITY_D
				WHERE
					CITY_SRC_ID = @CITYID

				IF @N_CITYNAME <> @CITYNAME OR @N_STATE_D_ID <> @STATE_D_ID
				BEGIN

					SET @ROWS_UPD = @ROWS_UPD + 1

					UPDATE
						CITY_D
					SET
						CITY_NAME = @CITYNAME
						, STATE_D_ID = @STATE_D_ID
						, LAST_UPDATE_DATE = GETDATE()
					WHERE
						CITY_SRC_ID = @CITYID

				END
				ELSE
				BEGIN

					SET @ROWS_SKIP = @ROWS_SKIP + 1

				END

			END

			FETCH NEXT FROM DB_CURSOR INTO @CITYID, @CITYNAME, @STATEPROVINCEID

		END

		CLOSE DB_CURSOR
		DEALLOCATE DB_CURSOR

		INSERT INTO [dbo].[RUNS] (RUN_NAME, RUN_DT, SOURCE_COLUMNS, ROWS_INS, ROWS_DEL, ROWS_UPD, ROWS_SKIP) 
			VALUES ('CITY_D', @NEWCHECKPOINT, @SOURCE_COLUMNS, @ROWS_INS, @ROWS_DEL, @ROWS_UPD, @ROWS_SKIP)

	END

END
GO
