CREATE OR ALTER PROCEDURE LOADER_CUSTOMER_CATEGORY_d AS 
BEGIN

--- CREATING LOADER FOR CUSTOMER_CATEGORY_D

	BEGIN
		DECLARE @CHECKPOINT DATETIME, @NEWCHECKPOINT DATETIME
		DECLARE @SOURCE_COLUMNS INT, @ROWS_INS INT, @ROWS_DEL INT, @ROWS_UPD INT, @ROWS_SKIP INT
		DECLARE @CUSTOMER_CATEGORY_D_ID INT, @CUSTOMERCATEGORYID INT, @CUSTOMERCATEGORYNAME NVARCHAR(50)
		DECLARE @N_CUSTOMERCATEGORYID INT, @N_CUSTOMERCATEGORYNAME NVARCHAR(50)

		SELECT 
			@CHECKPOINT = a.RUN_DT
		FROM
			(
				SELECT 
					MAX(b.RUN_DT) RUN_DT
				FROM
					(
						SELECT RUN_DT FROM [dbo].[RUNS] WHERE RUN_NAME = 'CUSTOMER_CATEGORY_D'
						UNION
						SELECT CONVERT([datetime], '1990-01-01 00:00:00') RUN_DT
					)b
			)a
		SELECT @NEWCHECKPOINT= GETDATE(), @SOURCE_COLUMNS = 0, @ROWS_INS = 0, @ROWS_DEL = 0, @ROWS_UPD = 0, @ROWS_SKIP = 0

		IF @CHECKPOINT = NULL
		BEGIN
			SET @CHECKPOINT = CONVERT([datetime], '1990-01-01 00:00:00')
		END

		DECLARE DB_CURSOR CURSOR FOR 
			SELECT 
				@CUSTOMERCATEGORYID
				, @CUSTOMERCATEGORYNAME
			FROM
				WideWorldImporters.[Sales].CustomerCategories
			FOR SYSTEM_TIME
				BETWEEN @CHECKPOINT AND @NEWCHECKPOINT
			ORDER BY
				CUSTOMERCATEGORYID, VALIDFROM

			OPEN DB_CURSOR
			FETCH NEXT FROM DB_CURSOR INTO @CUSTOMERCATEGORYID, @CUSTOMERCATEGORYNAME 

			WHILE @@FETCH_STATUS = 0
			BEGIN

				SET @SOURCE_COLUMNS = @SOURCE_COLUMNS + 1

				IF NOT EXISTS (SELECT @CUSTOMER_CATEGORY_D_ID FROM CUSTOMER_CATEGORY_D WHERE CATEGORY_SRC_ID = @CUSTOMERCATEGORYID)
				BEGIN
					SET @ROWS_INS = @ROWS_INS + 1

					INSERT INTO CUSTOMER_CATEGORY_D ( CATEGORY_NAME, CATEGORY_SRC_ID)
						VALUES (@CUSTOMERCATEGORYNAME, @CUSTOMERCATEGORYID)
				END
				ELSE 
				BEGIN

					SELECT
						@N_CUSTOMERCATEGORYID = CATEGORY_NAME
					FROM 
						CUSTOMER_CATEGORY_D
					WHERE 
						@CUSTOMER_CATEGORY_D_ID = @CUSTOMERCATEGORYID
					IF @CUSTOMERCATEGORYNAME <> @N_CUSTOMERCATEGORYNAME
					BEGIN
						SET @ROWS_UPD = @ROWS_UPD + 1
						
						UPDATE
							CUSTOMER_CATEGORY_D
						SET
							CATEGORY_NAME = @CUSTOMERCATEGORYNAME
							, LAST_UPDATE_DATE = GETDATE()
						WHERE
							CATEGORY_SRC_ID = @CUSTOMERCATEGORYID
					END
					ELSE
					BEGIN
						SET @ROWS_SKIP = @ROWS_SKIP + 1
					END
				END
				FETCH NEXT FROM DB_CURSOR INTO @CUSTOMERCATEGORYID, @CUSTOMERCATEGORYNAME
			END

			CLOSE DB_CURSOR
			DEALLOCATE DB_CURSOR

			INSERT INTO [dbo].[RUNS](RUN_NAME, RUN_DT, SOURCE_COLUMNS, ROWS_INS, ROWS_DEL, ROWS_UPD, ROWS_SKIP)
				VALUES ('CUSTOMER_CATEGORY_D', @NEWCHECKPOINT, @SOURCE_COLUMNS, @ROWS_INS, @ROWS_DEL, @ROWS_UPD, @ROWS_SKIP)

		END
		END
		GO










