--- let's create LOAD DELIVER_METHOD_D
CREATE OR ALTER PROCEDURE LOADER_DELIVERY_METHOD_D AS
BEGIN

	BEGIN
		DECLARE @CHECKPOINT DATETIME, @NEWCHECKPOINT DATETIME
		DECLARE @SOURCE_COLUMNS INT, @ROWS_INS INT, @ROWS_DEL INT, @ROWS_UPD INT, @ROWS_SKIP INT
		DECLARE @DELIVERY_METHOD_D_ID INT, @DELIVERYMETHODID INT, @DELIVERYMETHODNAME NVARCHAR(50)
		DECLARE @N_DELIVERYMETHODID INT, @N_DELIVERYMETHODNAME NVARCHAR(50)

		SELECT
			@CHECKPOINT = a.RUN_DT
		FROM 
			(
				SELECT 
					MAX(b.RUN_DT) RUN_DT
				FROM
					(
						SELECT RUN_DT FROM [dbo].[RUNS] WHERE RUN_NAME = 'DELIVERY_METHOD_D'
						UNION
						SELECT CONVERT ([datetime], '1990-01-01 00:00:00') RUN_DT
					)b
				)a
			SELECT @NEWCHECKPOINT = GETDATE(), @SOURCE_COLUMNS = 0, @ROWS_INS = 0, @ROWS_DEL = 0, @ROWS_UPD = 0, @ROWS_SKIP = 0

			IF @CHECKPOINT = NULL
			BEGIN
				SET @CHECKPOINT = CONvERT([datetime], '1990-01-01 00:00:00')
			END
		DECLARE DB_CURSOR CURSOR FOR
			SELECT
				@DELIVERYMETHODID
				, @DELIVERYMETHODNAME
			FROM
				WideWorldImporters.[Application].DeliveryMethods
			FOR SYSTEM_TIME
				BETWEEN @CHECKPOINT AND @NEWCHECKPOINT
			ORDER BY
				DELIVERYMETHODID, VALIDFROM

		OPEN DB_CURSOR 
		FETCH NEXT FROM DB_CURSOR INTO @DELIVERYMETHODID, @DELIVERYMETHODNAME

		WHILE @@FETCH_STATUS = 0
		BEGIN

			SET @SOURCE_COLUMNS = @SOURCE_COLUMNS + 1

			IF NOT EXISTS (SELECT @DELIVERY_METHOD_D_ID FROM DELIVERY_METHOD_D WHERE METHOD_SRC_ID = @DELIVERYMETHODID)
			BEGIN

				SET @ROWS_INS = @ROWS_INS + 1

				INSERT INTO DELIVERY_METHOD_D (METHOD_NAME, METHOD_SRC_ID)
					VALUES (@DELIVERYMETHODNAME, @DELIVERYMETHODID)

			END
			ELSE
			BEGIN

				SELECT
					@N_DELIVERYMETHODNAME = METHOD_NAME
				FROM
					DELIVERY_METHOD_D
				WHERE 
					METHOD_SRC_ID = @DELIVERYMETHODID

				IF @N_DELIVERYMETHODID <> @DELIVERYMETHODNAME
				BEGIN

					SET @ROWS_UPD = @ROWS_UPD + 1
					
					UPDATE
						DELIVERY_METHOD_D
					SET
						METHOD_NAME = @DELIVERYMETHODNAME
						, LAST_UPDATE_DATE = GETDATE()
					WHERE
						METHOD_SRC_ID = @DELIVERYMETHODID
			END
			ELSE
			BEGIN

				SET @ROWS_SKIP = @ROWS_SKIP + 1

			END
		END

		FETCH NEXT FROM DB_CURSOR INTO @DELIVERYMETHODID, @DELIVERYMETHODNAME

	END

	CLOSE DB_CURSOS 
	DEALLOCATE DB_CURSOR

	INSERT INTO [dbo].[RUNS] (RUN_NAME, RUN_DT, SOURCE_COLUMNS, ROWS_INS, ROWS_DEL, ROWS_UPD,ROWS_SKIP)
		VALUES ('DELIVERY_METHOD_D', @NEWCHECKPOINT, @SOURCE_COLUMNS, @ROWS_INS, @ROWS_DEL, @ROWS_UPD, @ROWS_SKIP)

	END
END
GO


